### ISSUE TITLE
Running your model

### ISSUE THREAD

**Issue by HappyDay-design** [azlaanmsamad/MultiAgentDQRNForDifferentTrafficDemands#1]
Thank you for sharing your code

Could you show me how to run, and test your model?

**Comment by TrinhTuanHung2021** [comment]
When I run single_train_main.py it had errors

Traceback (most recent call last):
  File "/home/osboxes/Desktop/MultiAgentDQRNForDifferentTrafficDemands/implementation/single_train_main.py", line 74, in <module>
    observation = env.reset()
  File "/home/osboxes/Desktop/MultiAgentDQRNForDifferentTrafficDemands/implementation/aienvs/Sumo/SumoGymAdapter.py", line 133, in reset
    self._startSUMO()
  File "/home/osboxes/Desktop/MultiAgentDQRNForDifferentTrafficDemands/implementation/aienvs/Sumo/SumoGymAdapter.py", line 208, in _startSUMO
    self._sumo_helper = SumoHelper(self._parameters, self._port, int(self._seed))
  File "/home/osboxes/Desktop/MultiAgentDQRNForDifferentTrafficDemands/implementation/aienvs/Sumo/SumoHelper.py", line 25, in __init__
    assert(self.scenario_check(self.parameters['scene']))
  File "/home/osboxes/Desktop/MultiAgentDQRNForDifferentTrafficDemands/implementation/aienvs/Sumo/SumoHelper.py", line 45, in scenario_check
    self._net_file = os.path.basename(glob.glob(self.scenario_path + '/*.net.xml')[0])
IndexError: list index out of range

**Comment by HappyDay-design** [comment]
Thank you very  much
I can run your model with gym==0.26.2 and Tensorflow==1.13.1
And change the path file in the implementation folder.
copy `aienvs` folder to the implementation folder.
copy `scenarios` folder to `implementation/aienvs/Sumo`
create the new test folder in `implementation/aienvs/Sumo`

![image](https://user-images.githubusercontent.com/82990411/193964543-1ea21273-baae-4399-a669-fe0851f273d5.png)
